apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: inventory-management-ui-solution
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: htts
      protocol: HTTP
    hosts:
    - "staging-inventory.cloudnativetoolkit.dev"
