apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: toolkit-prod
  labels:
    group: catalyst-tools
    grouping: garage-cloud-native-toolkit
spec:
  text: Prod
  location: BannerTop ##Other options are BannerBottom, BannerTopBottom
  color: '#fff'
  backgroundColor: green
