apiVersion: batch/v1
kind: Job
metadata:
  generateName: sync-pre-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: sync
          image: quay.io/ibmgaragecloud/ibmcloud-dev
          command:
            - "sleep"
          args:
            - "120"
          env:
            - name: SERVICE_NOW_URL
              value: ""
            - name: DEPLOYMENT
              value: nginx
