apiVersion: batch/v1
kind: Job
metadata:
  generateName: sync-pre-
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookFailed
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: sync
          image: quay.io/ibmgaragecloud/ibmcloud-dev
          command:
            - "/bin/echo"
          args:
            - "Sync started: ${DEPLOYMENT}"
          env:
            - name: SERVICE_NOW_URL
              value: ""
            - name: DEPLOYMENT
              value: nginx
