apiVersion: batch/v1
kind: Job
metadata:
  name: sync-success
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: sync
          image: quay.io/ibmgaragecloud/ibmcloud-dev
          command:
            - "/bin/echo"
          args:
            - "Sync successful: ${DEPLOYMENT}"
          env:
            - name: SERVICE_NOW_URL
              value: ""
            - name: DEPLOYMENT
              value: nginx
